name: Validate PR

on:
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, labeled]

env:
  IMAGE_TO_TEST: itzg/saml-auth-proxy:test-${{ github.repository_owner }}-${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run tests
        run: |
          go test ./...

      - name: Gather Docker metadata
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image')
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            itzg/saml-auth-proxy

      - name: Login to DockerHub
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        if: contains(github.event.pull_request.labels.*.name, 'ci/push-image')
        uses: docker/build-push-action@v2.7.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          pull: true
          push: true
          labels: ${{ steps.meta.outputs.labels }}
